#
# <  MewX's Homepage v3 - 12/28/2017 >
# This yml file refers several yml files, thanks to all open-source website projects.
#

# General setting
markdown: kramdown
encoding: utf-8

# Site info
baseurl: https://www.mewx.org/
#baseurl: http://127.0.0.1:4000/
paginate: 10
permalink: blog/:year:month/:title/
exclude: ["README.md", "changelog.md", "Gemfile.lock"]
gems: [jekyll-paginate]

# Blog info
title : MewX's Homepage
author: MewX
email : mewx(at)mewx(dot)org
cdn   : https://www.mewx.org/
#cdn   : http://127.0.0.1:4000/
